# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=250)),
                ('album_artist', models.CharField(max_length=250)),
                ('ablum_count', models.IntegerField()),
                ('album_logo', models.CharField(max_length=1000)),
                ('album_genre', models.CharField(max_length=250)),
                ('album_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('song_artists', models.CharField(max_length=250)),
                ('song_genre', models.CharField(max_length=250)),
                ('song_composer', models.CharField(max_length=250)),
                ('song_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('song_type', models.CharField(max_length=10)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
