# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170526_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_count',
            field=models.IntegerField(default=1),
        ),
    ]
