# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170526_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='song_composer',
        ),
    ]
